import { BarChart3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useNavigate } from "react-router-dom";

export default function TermsPage() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-background">
      <nav className="border-b bg-background/80 backdrop-blur-sm">
        <div className="mx-auto flex h-16 max-w-4xl items-center gap-3 px-6">
          <button onClick={() => navigate("/")} className="flex items-center gap-2 font-bold">
            <BarChart3 className="h-5 w-5 text-primary" />
            Ceaser
          </button>
        </div>
      </nav>
      <div className="mx-auto max-w-3xl px-6 py-12 prose prose-invert">
        <h1>Terms of Service</h1>
        <p><em>Last updated: March 2026</em></p>

        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using Ceaser ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>

        <h2>2. Service Description</h2>
        <p>Ceaser is an AI-powered data analytics platform that allows users to query databases and files using natural language. The Service generates SQL queries, Python code, visualizations, and reports based on user input.</p>

        <h2>3. Account Responsibilities</h2>
        <p>You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account.</p>

        <h2>4. Data & Privacy</h2>
        <p>We do not store your query results unless you explicitly save a report. Database credentials are encrypted at rest. See our Privacy Policy for details.</p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to other users' data; (c) reverse engineer the Service; (d) exceed usage limits of your plan.</p>

        <h2>6. Read-Only Access</h2>
        <p>Ceaser executes only SELECT queries against your databases. INSERT, UPDATE, DELETE, and DDL operations are blocked at multiple layers. We are not responsible for any data issues in databases you connect.</p>

        <h2>7. AI-Generated Content</h2>
        <p>Results generated by our AI may contain errors. You are responsible for verifying the accuracy of all generated queries, analysis, and reports before making business decisions.</p>

        <h2>8. Subscription & Billing</h2>
        <p>Paid plans are billed monthly or annually. You may cancel at any time. Refunds are provided on a case-by-case basis within 14 days of payment.</p>

        <h2>9. Limitation of Liability</h2>
        <p>The Service is provided "as is" without warranties. We are not liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>

        <h2>10. Changes to Terms</h2>
        <p>We may update these terms at any time. Continued use after changes constitutes acceptance.</p>

        <h2>Contact</h2>
        <p>Questions? Contact us at support@ceaser.ai</p>
      </div>
    </div>
  );
}
